### ISSUE TITLE
[FEAT] - Modify the Bot Direct message.

### ISSUE THREAD

**Issue by Nikolai558** [Nikolai558/FE-BUDDYBot#10]
## Describe the solution you'd like
Modify the bot DM message to tell the user Who the bot is with i.e. -> FE-Buddy discord server.
The message that is sent when a user joins that does not have their vatusa linked, needs re-worked.

**Comment by KSanders7070** [comment]
Hello, I am an automated program that is here to help you get your FE-Buddy Discord permissions/roles setup.

To do this, I need you to sync your Discord account with the VATUSA Discord server; You may do this by going to your VATUSA profile HERE(link) > “VATUSA Discord Link”.

When you are complete, please go to the FE-Buddy Discord #assign-my-roles channel and complete the !GR command.

If you are unable to do this, please private message one of the Administrators of the discord.
